{% set name = "pysyncrosim" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysyncrosim-{{ version }}.tar.gz
  sha256: f8a08fb83a625f7d5374e8c714460f7a4b5d0983728109208b52a7f3fd307393

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pandas
    - numpy
    - rasterio
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - rasterio

test:
  imports:
    - pysyncrosim
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://syncrosim.com/
  summary: Python interface to SyncroSim
  license: MIT
  license_file: LICENSE
  doc_url: https://pysyncrosim.readthedocs.io/en/latest/
  dev_url: https://github.com/syncrosim/pysyncrosim/

extra:
  recipe-maintainers:
    - katieb1
