{% set name = "pysyncrosim" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysyncrosim-{{ version }}.tar.gz
  sha256: 413f6a5adc6a4f42fde8bf3d8760c945ef6b5b24274006a2e6cddc61a020a607

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - pandas
    - numpy
    - rasterio
  run:
    - python >=3.8
    - pandas
    - numpy
    - rasterio

test:
  imports:
    - pysyncrosim
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://syncrosim.com/
  summary: Python interface to SyncroSim
  license: MIT
  license_file: LICENSE
  doc_url: https://pysyncrosim.readthedocs.io/en/latest/
  dev_url: https://github.com/syncrosim/pysyncrosim/

extra:
  recipe-maintainers:
    - katieb1
