{% set name = "pysyncrosim" %}
{% set version = "2.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysyncrosim-{{ version }}.tar.gz
  sha256: f246e1f9e17c1b0299e650244f89ebac2857605f037edfc529dc6f6ea775f239

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pandas
    - numpy
    - rasterio
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - rasterio

test:
  imports:
    - pysyncrosim
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://syncrosim.com/
  summary: Python interface to SyncroSim
  license: MIT
  license_file: LICENSE
  doc_url: https://pysyncrosim.readthedocs.io/en/latest/
  dev_url: https://github.com/syncrosim/pysyncrosim/

extra:
  recipe-maintainers:
    - katieb1
    - vickimzhang
    - spearmangillman
